### ISSUE TITLE
cURL error 28: Operation timed out after 3000 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by pesseyjulien** [GetStream/stream-chat-php#101]
Hi,

I'm using the php sdk but I often get the following error : 

GuzzleHttp\Exception\ConnectException
cURL error 28: Operation timed out after 3000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://chat.stream-io-api.com/channels?api_key=XXX

Any idea how to fix this ?

Thanks in advance,
Julien

**Comment by ferhatelmas** [comment]
`public function __construct(string $apiKey, string $apiSecret, string $apiVersion = null, string $location = null, float $timeout = null)`

You can adjust timeout according to your network needs while creating your client as in the last parameter.
