### ISSUE TITLE
verifyWebhook seems not to work properly 

### ISSUE THREAD

**Issue by tfs-guy** [GetStream/stream-chat-php#115]
Hi, as shown [here](https://getstream.io/chat/docs/php/webhooks_overview/?language=php#signature) we want to validate the incoming content from the webhook.

This is the code that we are using:
```php
class GetStreamValidator implements SignatureValidator
{
    public function __construct(
        protected GetStreamService $getStreamService,
    ) {}

    public function isValid(Request $request, WebhookConfig $config): bool
    {
        $signature = $request->header('X-Signature');

        $body = json_encode($request->all());

        return $this->getStreamService->verifyWebhook($body, $signature);
    }
}
```

With our `getStreamService->verifyWebhook` just passing the parameters through to your method :
```php
class GetStreamService
{
    public function __construct(
        protected Client $client,
    ) {}

    // ...

  public function verifyWebhook(string $requestBody, string $signature): bool
    {
        return $this->client->verifyWebhook($requestBody, $signature);
    }
}
```

The odd thing is now, that this function always returns `false` even though we're using the actual request that we receive after we wrote something in our chat. This is the actual request that we receive to the url that we configured [here](https://getstream.io/chat/docs/php/webhooks_overview/?language=php#configuration):
![actual request](https://github.com/GetStream/stream-chat-php/assets/77271943/a6fd8aa7-56f0-47e2-9a89-0a600082dea9)

I don't know if this is important but we [enabled teams for our application](https://getstream.io/chat/docs/php/multi_tenant_chat/?language=php#enable-teams-for-your-application). We're using version 3.3.0 of this package in a laravel application.

We don't know what we're doing wrong. I tripple checked our key and secret, to ensure that they are correct. But the given signature in the request from above seems not to match with the given body.

Can you help us on this one please?

**Comment by JimmyPettersson85** [comment]
Hey @tfs-guy, this is just a guess but the line `$body = json_encode($request->all());` seems suspect. In order for the signatures to match the request body string needs to be identical (as in byte-for-byte) to the request body. Could `$request->all()` or `json_encode` change the body in some way like the order of the keys or something?

**Comment by tfs-guy** [comment]
Hey @JimmyPettersson85 thanks for your fast response.

I also tried using `$request->getContent()` as suggested [here](https://stackoverflow.com/a/31669672/11485326). Both are not working. 

I also just tried to copy the body directly from the body of our request (logged via telescope) like this:
![image](https://github.com/GetStream/stream-chat-php/assets/77271943/18c101bc-46ee-42ad-be2d-c19729ebe336)

But this also fails... even though it looks pretty much the same as it is shown [here](https://getstream.io/chat/docs/php/webhook_events/?language=php#message.new).

**Comment by JimmyPettersson85** [comment]
hey @tfs-guy

I've gotten it to work locally so I dont think there's something wrong with how the signature checking works. The body in your example seems to contain newlines (`\n`) which the raw response doesn't. As for `$request->getContent()` I cant really say as I'm not familiar with that.

![image](https://github.com/GetStream/stream-chat-php/assets/953852/102abf95-da61-4f71-968f-f36e83ea9e8d)

**Comment by tfs-guy** [comment]
Hey @JimmyPettersson85 ,
thank you, there were escape signs that shouldn't have been there.

But in your example it looks like  you used the `apiSecret` to verify. In the code from the package it uses the `apiKey`:
![image](https://github.com/GetStream/stream-chat-php/assets/77271943/cba312eb-3279-4319-9e6f-f4084dc05f38)

If I change this in my vendor folder to apiSecret it works. Otherwise even without any newlines or escape chars it still returns false. So it seems like a bug in the `verifyWebhook` method?

**Comment by tfs-guy** [comment]
No wait sorry. I just checked the code in this repository and it clearly says `apiSecret`. Don't know where the `apiKey` in my vendor folder comes from.

Thank you very much for your help :)
