### ISSUE TITLE
Regex Pattern For Searching Message Substring

### ISSUE THREAD

**Issue by Rajat117** [GetStream/stream-chat-php#16]
Currently, we need to add the full word so we can get the search result for our message. Can't we get messages which contain the substring of the word we are typing?

E.g 
$response = $client->search(
	$filters,
	'Hey',
	['limit' => 2, 'offset' => 0]
);

This will list all messages which contain the word hey.

is there a way where we could just enter 'ey' keyword & it will give all messages containing that string?

**Comment by ferhatelmas** [comment]
This works by default and also #33 for filter support.
