### ISSUE TITLE
After channel creation. Is there a way to change ownership of channel?

### ISSUE THREAD

**Issue by Rajat117** [GetStream/stream-chat-php#17]
$data = [
    'image' => 'https://path/to/image2',
    'roles' => ['elon'=> 'moderator', 'gwynne'=> 'moderator']
];

$update = $channel->update($data);

The method here shows how to change the roles of the user server-side. But it's not changing roles And if possible this way do I have any method to change ownership of the channel

**Comment by ferhatelmas** [comment]
see https://github.com/GetStream/stream-chat-php/blob/master/lib/GetStream/StreamChat/Channel.php#L277
