### ISSUE TITLE
Setting timeout when initialising the SDK

### ISSUE THREAD

**Issue by dongido001** [GetStream/stream-chat-php#2]
Currently, when initializing the SDK with a timeout value, you have to do something like:

```
        // Initialize Stream Chat SDK
        $client = new StreamClient(
            getenv("STREAM_API_KEY"), 
            getenv("STREAM_API_SECRET"),
            '',
            '',
            9 // timeout
        );
```
This way the `apiVersion` and `location` will be overwriten with empty string unless the users sets it when initialzing the SDK. 

Would it be better to make it an array instead and the keys are then merged? 

something like:

```
        // Initialize Stream Chat SDK
        $client = new StreamClient(
            getenv("STREAM_API_KEY"), 
            getenv("STREAM_API_SECRET"),
            ['timeout' => 9]
        );
```

**Comment by tbarbugli** [comment]
The idea is to use `null` to not change default value but I get your point. @pterk this seems a good improvement, thoughts?

**Comment by pterk** [comment]
I like it, personally. There's something to be said that an $options array obscures the available options a bit and the null options sort of document the code. Also, maybe consider the similarity across the various clients?

**Comment by dongido001** [comment]
Right, didn't remember the `null` not changing the default.
