### ISSUE TITLE
cURL error 28: Resolving timed out after 3000 milliseconds 

### ISSUE THREAD

**Issue by Himanshu-addweb** [GetStream/stream-chat-php#20]
Most of the times, I am getting this error

`cURL error 28: Resolving timed out after 3000 milliseconds ` while using this package for creating channel and adding members in it

**Comment by tbarbugli** [comment]
this can happen if you connect to a remote API endpoint (ie. use US endpoint from EU or Asia). @pterk can you add a code example / docs about how you set $location?

**Comment by Himanshu-addweb** [comment]
I am not adding $location in channel initialization or create, can you just let me know where and what location needs to be added to prevent his issue??

$channel = $this->streamChatClient->Channel("messaging", $journeyArray['_id'], $journeyChannelInfo);

**Comment by pterk** [comment]
Hi @Himanshu-addweb,

You should be able to use this:

$this->streamChatClient->setLocation($location);

See here for more information about available locations.

https://getstream.io/chat/docs/multi_region/?language=python&q=locations

**Comment by pterk** [comment]
Added an example to the readme, updated the docs to include a PHP example and linked to it from the readme.
