### ISSUE TITLE
I am facing error while adding members to any already created channel

### ISSUE THREAD

**Issue by Himanshu-addweb** [GetStream/stream-chat-php#21]
I am facing below error while i have channel already created, but I am adding new members in it:

"{"code":4,"message":"UpdateChannel failed with error: \"could not find user 972214ab-3df2-42c5-9983-f95fe3221379 from add_members\"","StatusCode":400,"duration":"0.00ms"}"

Should I call `createToken` method first or any newly adding user in existing channel???

**Comment by ferhatelmas** [comment]
Sounds like app specific and a bit old, closing. If still exists, please contact at https://getstream.io/support
