### ISSUE TITLE
Don't require created_by in get of getOrCreateChannel

### ISSUE THREAD

**Issue by Himanshu-addweb** [GetStream/stream-chat-php#22]
I am facing below error while adding members in channel:

"{"code":4,"message":"GetOrCreateChannel failed with error: \"either data.created_by or data.created_by_id must be provided when using server side auth.\"","StatusCode":400,"duration":"0.00ms"}"

I don't know why this issue is displaying

**Comment by ferhatelmas** [comment]
Could you share your code snippet for the relevant part ? It would be easier to point the issue.

**Comment by Himanshu-addweb** [comment]
$journeyChannelInfo = [
                "name" => $journeyArray['title']
            ];
            $channel = $this->streamChatClient->Channel("messaging", $journeyArray['_id'], $journeyChannelInfo);
            $channelResponse = $channel->query([
                "watch" => false,   
                "state" => false,
                "presence" => false
            ]);

**Comment by Himanshu-addweb** [comment]
And error is displaying in `query`method

**Comment by ferhatelmas** [comment]
@Himanshu-addweb this's known and needs fixing. If the channel is already created, `created_by` or `created_by_id` isn't required but due to implementation and easiness, it is still required. 

As a workaround for now, you can pass the id as the fourth parameter while calling channel constructor.

**Comment by ferhatelmas** [comment]
@Himanshu-addweb edited the code snippet for better rendering, FYI.

**Comment by ferhatelmas** [comment]
I will close this in favor of suggesting `queryChannels`.
