### ISSUE TITLE
location setting is not effect at all

### ISSUE THREAD

**Issue by giautm** [GetStream/stream-chat-php#25]
API call still going to `http://chat-us-east-1.stream-io-api.com`

https://github.com/GetStream/stream-chat-php/blob/09b6862ffb33959fa806fc28d591084291912959/lib/GetStream/StreamChat/Client.php#L119-L124

Correct base URL for Singapore is `https://chat-proxy-singapore.stream-io-api.com`

gz#5831

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/5831'>Zendesk ticket #5831</a>:<br><br>Hi Giautm

Thanks for reaching to us.

 `const API_ENDPOINT = 'chat-us-east-1.stream-io-api.com';`

This should be replaced by the location.

https://github.com/GetStream/stream-chat-php/blob/09b6862ffb33959fa806fc28d591084291912959/lib/GetStream/StreamChat/Client.php#L119-L124
​
Can you check for BaseURL? Please let me know if this has been set up.

    client.setBaseURL('https://chat-proxy-singapore.stream-io-api.com');

Let me also check the value of STREAM_BASE_CHAT_URL.

Cheers
Seetha

**Comment by giautm** [comment]
Currently, I workaround by setting `STREAM_BASE_CHAT_URL` on environment. I report this to allow set base URL from location when initial client:
https://github.com/GetStream/stream-chat-php/blob/09b6862ffb33959fa806fc28d591084291912959/lib/GetStream/StreamChat/Client.php#L68

**Comment by tbarbugli** [comment]
@giautm thank you for reporting this 👍 We are going to make this consistent with the other API clients.
