### ISSUE TITLE
How to get full response with `getChannel` method?

### ISSUE THREAD

**Issue by SviatKuzma** [GetStream/stream-chat-php#32]
Hi guys,
`return $client->getChannel('one_to_one', $channelId);`
returns me only channel ID 
`{
    "success": true,
    "data": {
        "id": "28434226"
    }
}`

How I can get full response data of this channel(what method)?

By the way, 
code - 
`return $oldChannel->query(['state' => true]);`
returns - 
>         "name": "Exception",
>       "message": "{\"code\":4,\"message\":\"GetOrCreateChannel failed with error: \\\"expected object for field \\\"data\\\" but got array\\\"\",\"StatusCode\":400,\"duration\":\"0.00ms\",\"more_info\":\"https://getstream.io/chat/docs/api_errors_response\"}",

gz#8093

**Comment by SviatKuzma** [comment]
102881

**Comment by ferhatelmas** [comment]
@SviatKuzma you need to add a `create` call to initialize the data structure properly before `query` call which is a noop if exists.

```
$channel = $client->getChannel($channelType, $channelId);
$channel->create($createdById);
$channel->query();
```

If you know your channel exists certainly, go with `$client->queryChannels(['cid' => 'your cid']);` directly.
