### ISSUE TITLE
Query all channels without any conditions(filters)

### ISSUE THREAD

**Issue by SviatKuzma** [GetStream/stream-chat-php#35]
`$client->queryChannels();` - returns me error

> Too few arguments to function GetStream\\StreamChat\\Client::queryChannels()

`$client->queryChannels([]);` - returns me error

> QueryChannels failed with error: \\\"expected object for field \\\"filter_conditions\\\" but got array

`$client->queryChannels([]);` - returns me error

> "syntax error, unexpected '{'",

Can you please update this method as you did with #27 ?

gz#8192

**Comment by ferhatelmas** [comment]
@SviatKuzma I understand your need but it's not feasible for this endpoint because it's heavy, please pass some filters.

We can improve validation in SDK a bit more though.
