### ISSUE TITLE
Get Flagged Message History

### ISSUE THREAD

**Issue by rebeccamcdougal** [GetStream/stream-chat-php#37]
I've gone through the docs but haven't seemed to have found it. Is there a way to get a list of the flagged messages and the history of who has reviewed them, outside of the Get Stream dashboard? The flagged attribute doesn't even seem to show up on the messages when watched in a channel.

gz#9988

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/9988'>Zendesk ticket #9988</a>:<br><br>Hi there,

Sorry, there isn't a way to query these types of messages directly (the dashboard is the best option in this regard). That being said, You can also utilize our webhooks to listen for flagged events if that better fits your use case. Please refer to this documentation for more details - https://getstream.io/chat/docs/webhook_events/?language=js

**Comment by ferhatelmas** [comment]
I will close this one since it's not supported in API, and nothing to do in SDK.
