### ISSUE TITLE
Unflag message not working. 

### ISSUE THREAD

**Issue by rebeccamcdougal** [GetStream/stream-chat-php#53]
I'm using the queryMessageFlags call to get a list of flagged messages, but if I then try to use the unFlagMessage call to unflag the message that was just returned it fails with the error 'Unflag failed with error: "message xxxxxxx is not flagged"'

gz#12408

**Comment by shodgetts** [comment]
Agent comment from Zachery Converse in <a href='https://getstream.zendesk.com/agent/tickets/12408'>Zendesk ticket #12408</a>:<br><br>Hi Rebecca,

Thanks for reaching out. Let me take a look into this and get back to you, soon.

Cheers,
-Zachery
 Getstream.io
<br><p><em><small>°°°</small></em></p>

**Comment by shodgetts** [comment]
Agent comment from Zachery Converse in <a href='https://getstream.zendesk.com/agent/tickets/12408'>Zendesk ticket #12408</a>:<br><br>Hi Rebecca,

unflagMeaage takes a string messageId - are you able to confirm that this is what is being passed? A code snippet would be super helpful if you're able to provide one. Feel free to provide any additional information that may help debug as well.

Cheers,
-Zachery
 Getstream.io
<br><p><em><small>°°°</small></em></p>

**Comment by rebeccamcdougal** [comment]
Yes a string with a valid message id is being passed in. This is the code I'm using

`$flagged_messages = $client->queryMessageFlags(["channel_cid" => "messaging:channel_105634751"]);

foreach ($flagged_messages['flags'] as $item) {
  $flag = $client->unFlagMessage($item['message']['id'], ['user_id' => 'user_10']);
}`

This is the error 

Error: [GetStream\StreamChat\StreamException] {"code":4,"message":"Unflag failed with error: \"message e73fd62b-c432-489b-8a63-73e089e53980 is not flaged\"","StatusCode":400,"duration":"0.00ms","more_info":"https://getstream.io/chat/docs/api_errors_response"}

**Comment by ferhatelmas** [comment]
@rebeccamcdougal You get all flags (message+user pair) but then you try to remove flag from a specific user. There flag can be from a different user so you need to use user id of the flag to remove it i.e. `$client->unFlagMessage($item['message']['id'], ['user_id' => $item['user']['id']);`

**Comment by rebeccamcdougal** [comment]
So would that mean that there isn't a way to unflag those that were flagged by the AI, so flagged_by_automod set to true?

**Comment by ferhatelmas** [comment]
That's correct as current behavior. Checking with PM to permit it or not. Stay tuned, please!
